CREATE TABLE BEBIDA(
id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
nombre VARCHAR(50) NOT NULL,
descripcion VARCHAR(250)NOT NULL,
costo INTEGER NOT NULL
);

CREATE TABLE TOPPING(
id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
nombre VARCHAR(50) NOT NULL,
descripcion VARCHR(250) NOT NULL,
costo INTEGER NOT NULL
);
